### ISSUE TITLE
Cairo

### ISSUE THREAD

**Issue by facferreira** [HACKERCHANNEL/PSL1GHT#46]
I am using the Cairo sample, I added some more things of cairo to the sample, but it is very slow, how can I do in order to speed up? Anyone can give me a sample of it?

**Comment by Jiboo** [comment]
Hello,

Could any experimented cell programmer could write an article on the wiki?
To reply some questions that new comer (like me) would ask:
What's a ppu/spu? If i have no thread in my program will i use only one core of the ppu?

facanferff: I think it is mostly because we are using the cpu (ppu?) and not the rsx. When we will have access to opengl function with psl1ght we might get a hardware accelerated cairo.

To gain some fps, i think that you can create / destoy the surfaces in the main and not do that in each frame.

**Comment by Parlane** [comment]
It is most likely slow due to using a framebuffer, if you want any kind of speed ind rawing you need to use rsx quads etc. Cairo was a small fork in the road to get something on screen with what we had at the time, that being a simple framebuffer.
